### ISSUE TITLE
Ideas

### ISSUE THREAD

**Issue by nanexcool** [makerdao/price-feed#1]
- Should expiration be mandatory? If so, no need for `poke`, only `prod`
- Medianizer poke... also mandatory?
  - Store medianizer address or pass as function param?
  - Assert that medianizer poke worked? Or silently fail/pass?

Leaning towards: mandatory expiration, medianizer address as function param, don't complain if medianizer poke fails.

Also, create `DSRead` interface?
```
interface DSRead {
    function peek() constant returns (bytes32,bool);
    function read() constant returns (bytes32);
}
```

**Comment by tomedwardsmith** [comment]
Hi @nanexcool  - this is an old one - can we close it, or is it still relevant?
